# Generated by Django 5.1 on 2025-08-20 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0002_pledge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pledge',
            name='amount',
        ),
        migrations.AddField(
            model_name='pledge',
            name='comment',
            field=models.CharField(default='', max_length=200),
        ),
    ]
