# Generated by Django 5.2.5 on 2025-08-20 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0003_remove_pledge_amount_pledge_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
